# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420252fe0e62d6fc312fe306a733a8f38909af17fdbf358e0ff9523aac49a2a9c33b505aa6cf711d0b1c7f287bcc6bd0bbc37273cdc50612191570da2cc11a3f

test:
  secret_key_base: 122cf66cd48b67ebd59c2e248dd1a23b902faf98c13fb68ed8b127b5bd0a6e319cb9e4539eeb59205ff4855c5a509d2aed6af26f47716197c7067a5020780fc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
